// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module dual_faucet::drop_record {
    friend dual_faucet::fungible_asset_coin_dual_faucet_create_logic;
    friend dual_faucet::fungible_asset_coin_dual_faucet_drop_logic;
    friend dual_faucet::fungible_asset_coin_dual_faucet_replenish_logic;
    friend dual_faucet::fungible_asset_coin_dual_faucet;

    const EDataTooLong: u64 = 102;

    struct DropRecord has store {
        account_address: address,
        last_drop_time: u64,
    }

    public fun account_address(drop_record: &DropRecord): address {
        drop_record.account_address
    }

    public fun last_drop_time(drop_record: &DropRecord): u64 {
        drop_record.last_drop_time
    }

    public(friend) fun set_last_drop_time(drop_record: &mut DropRecord, last_drop_time: u64) {
        drop_record.last_drop_time = last_drop_time;
    }

    public(friend) fun new_drop_record(
        account_address: address,
        last_drop_time: u64,
    ): DropRecord {
        DropRecord {
            account_address,
            last_drop_time,
        }
    }

    public(friend) fun drop_drop_record(drop_record: DropRecord) {
        let DropRecord {
            account_address: _,
            last_drop_time: _,
        } = drop_record;
    }


}
