// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module dual_faucet::fa_coin_dual_faucet_created {

    use dual_faucet::fungible_asset_coin_dual_faucet::{Self, FACoinDualFaucetCreated};
    use std::option;
    use std::string::String;

    public fun id(fa_coin_dual_faucet_created: &FACoinDualFaucetCreated): option::Option<address> {
        fungible_asset_coin_dual_faucet::fa_coin_dual_faucet_created_id(fa_coin_dual_faucet_created)
    }

    public fun provider(fa_coin_dual_faucet_created: &FACoinDualFaucetCreated): address {
        fungible_asset_coin_dual_faucet::fa_coin_dual_faucet_created_provider(fa_coin_dual_faucet_created)
    }

    public fun x_token_type(fa_coin_dual_faucet_created: &FACoinDualFaucetCreated): address {
        fungible_asset_coin_dual_faucet::fa_coin_dual_faucet_created_x_token_type(fa_coin_dual_faucet_created)
    }

    public fun y_token_type(fa_coin_dual_faucet_created: &FACoinDualFaucetCreated): String {
        fungible_asset_coin_dual_faucet::fa_coin_dual_faucet_created_y_token_type(fa_coin_dual_faucet_created)
    }

    public fun x_amount(fa_coin_dual_faucet_created: &FACoinDualFaucetCreated): u64 {
        fungible_asset_coin_dual_faucet::fa_coin_dual_faucet_created_x_amount(fa_coin_dual_faucet_created)
    }

    public fun y_amount(fa_coin_dual_faucet_created: &FACoinDualFaucetCreated): u64 {
        fungible_asset_coin_dual_faucet::fa_coin_dual_faucet_created_y_amount(fa_coin_dual_faucet_created)
    }

}
