// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module dual_faucet::fa_coin_dual_faucet_replenished {

    use dual_faucet::fungible_asset_coin_dual_faucet::{Self, FACoinDualFaucetReplenished};
    use std::string::String;

    public fun id(fa_coin_dual_faucet_replenished: &FACoinDualFaucetReplenished): address {
        fungible_asset_coin_dual_faucet::fa_coin_dual_faucet_replenished_id(fa_coin_dual_faucet_replenished)
    }

    public fun provider(fa_coin_dual_faucet_replenished: &FACoinDualFaucetReplenished): address {
        fungible_asset_coin_dual_faucet::fa_coin_dual_faucet_replenished_provider(fa_coin_dual_faucet_replenished)
    }

    public fun x_token_type(fa_coin_dual_faucet_replenished: &FACoinDualFaucetReplenished): address {
        fungible_asset_coin_dual_faucet::fa_coin_dual_faucet_replenished_x_token_type(fa_coin_dual_faucet_replenished)
    }

    public fun y_token_type(fa_coin_dual_faucet_replenished: &FACoinDualFaucetReplenished): String {
        fungible_asset_coin_dual_faucet::fa_coin_dual_faucet_replenished_y_token_type(fa_coin_dual_faucet_replenished)
    }

    public fun x_amount(fa_coin_dual_faucet_replenished: &FACoinDualFaucetReplenished): u64 {
        fungible_asset_coin_dual_faucet::fa_coin_dual_faucet_replenished_x_amount(fa_coin_dual_faucet_replenished)
    }

    public fun y_amount(fa_coin_dual_faucet_replenished: &FACoinDualFaucetReplenished): u64 {
        fungible_asset_coin_dual_faucet::fa_coin_dual_faucet_replenished_y_amount(fa_coin_dual_faucet_replenished)
    }

}
