// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module dual_faucet::fa_coin_dual_faucet_dropped {

    use dual_faucet::fungible_asset_coin_dual_faucet::{Self, FACoinDualFaucetDropped};
    use std::string::String;

    public fun id(fa_coin_dual_faucet_dropped: &FACoinDualFaucetDropped): address {
        fungible_asset_coin_dual_faucet::fa_coin_dual_faucet_dropped_id(fa_coin_dual_faucet_dropped)
    }

    public fun receiver(fa_coin_dual_faucet_dropped: &FACoinDualFaucetDropped): address {
        fungible_asset_coin_dual_faucet::fa_coin_dual_faucet_dropped_receiver(fa_coin_dual_faucet_dropped)
    }

    public fun x_amount(fa_coin_dual_faucet_dropped: &FACoinDualFaucetDropped): u64 {
        fungible_asset_coin_dual_faucet::fa_coin_dual_faucet_dropped_x_amount(fa_coin_dual_faucet_dropped)
    }

    public fun y_amount(fa_coin_dual_faucet_dropped: &FACoinDualFaucetDropped): u64 {
        fungible_asset_coin_dual_faucet::fa_coin_dual_faucet_dropped_y_amount(fa_coin_dual_faucet_dropped)
    }

    public fun x_token_type(fa_coin_dual_faucet_dropped: &FACoinDualFaucetDropped): address {
        fungible_asset_coin_dual_faucet::fa_coin_dual_faucet_dropped_x_token_type(fa_coin_dual_faucet_dropped)
    }

    public fun y_token_type(fa_coin_dual_faucet_dropped: &FACoinDualFaucetDropped): String {
        fungible_asset_coin_dual_faucet::fa_coin_dual_faucet_dropped_y_token_type(fa_coin_dual_faucet_dropped)
    }

}
