// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module dual_faucet::fungible_asset_coin_dual_faucet {
    use aptos_framework::account;
    use aptos_framework::coin::Coin;
    use aptos_framework::event;
    use aptos_framework::fungible_asset::FungibleStore;
    use aptos_framework::object::{Self, Object};
    use dual_faucet::genesis_account;
    use dual_faucet::pass_object;
    use std::option;
    use std::string::String;
    friend dual_faucet::fungible_asset_coin_dual_faucet_create_logic;
    friend dual_faucet::fungible_asset_coin_dual_faucet_drop_logic;
    friend dual_faucet::fungible_asset_coin_dual_faucet_aggregate;

    friend dual_faucet::fungible_asset_coin_dual_faucet_accessor;

    const EDataTooLong: u64 = 102;
    const EInappropriateVersion: u64 = 103;
    const ENotInitialized: u64 = 110;

    struct Events has key {
        fa_coin_dual_faucet_created_handle: event::EventHandle<FACoinDualFaucetCreated>,
        fa_coin_dual_faucet_dropped_handle: event::EventHandle<FACoinDualFaucetDropped>,
    }

    public fun initialize(account: &signer) {
        genesis_account::assert_genesis_account(account);

        let res_account = genesis_account::resource_account_signer();
        move_to(&res_account, Events {
            fa_coin_dual_faucet_created_handle: account::new_event_handle<FACoinDualFaucetCreated>(&res_account),
            fa_coin_dual_faucet_dropped_handle: account::new_event_handle<FACoinDualFaucetDropped>(&res_account),
        });

    }

    #[resource_group_member(group = aptos_framework::object::ObjectGroup)]
    struct FungibleAssetCoinDualFaucet<phantom Y> has key {
        version: u64,
        x_reserve: Object<FungibleStore>,
        y_reserve: Coin<Y>,
    }

    #[resource_group_member(group = aptos_framework::object::ObjectGroup)]
    struct ObjectController has key {
        extend_ref: object::ExtendRef,
        delete_ref: object::DeleteRef,
        transfer_ref: object::TransferRef,
    }


    public(friend) fun save_object_controller(
        object_signer: &signer,
        extend_ref: object::ExtendRef,
        delete_ref: object::DeleteRef,
        transfer_ref: object::TransferRef,
    ) {
        move_to(
            object_signer,
            ObjectController {
                extend_ref,
                delete_ref,
                transfer_ref
            }
        )
    }

    public fun version<Y>(fungible_asset_coin_dual_faucet: &FungibleAssetCoinDualFaucet<Y>): u64 {
        fungible_asset_coin_dual_faucet.version
    }

    public(friend) fun x_reserve<Y>(fungible_asset_coin_dual_faucet: &FungibleAssetCoinDualFaucet<Y>): Object<FungibleStore> {
        fungible_asset_coin_dual_faucet.x_reserve
    }

    public(friend) fun set_x_reserve<Y>(fungible_asset_coin_dual_faucet: &mut FungibleAssetCoinDualFaucet<Y>, x_reserve: Object<FungibleStore>) {
        fungible_asset_coin_dual_faucet.x_reserve = x_reserve;
    }

    public(friend) fun borrow_y_reserve<Y>(fungible_asset_coin_dual_faucet: &FungibleAssetCoinDualFaucet<Y>): &Coin<Y> {
        &fungible_asset_coin_dual_faucet.y_reserve
    }

    public(friend) fun borrow_mut_y_reserve<Y>(fungible_asset_coin_dual_faucet: &mut FungibleAssetCoinDualFaucet<Y>): &mut Coin<Y> {
        &mut fungible_asset_coin_dual_faucet.y_reserve
    }

    public(friend) fun new_fungible_asset_coin_dual_faucet<Y>(
        x_reserve: Object<FungibleStore>,
    ): FungibleAssetCoinDualFaucet<Y> {
        FungibleAssetCoinDualFaucet {
            version: 0,
            x_reserve,
            y_reserve: aptos_framework::coin::zero(),
        }
    }

    struct FACoinDualFaucetCreated has store, drop {
        id: option::Option<address>,
        provider: address,
        x_token_type: address,
        y_token_type: String,
        x_amount: u64,
        y_amount: u64,
    }

    public fun fa_coin_dual_faucet_created_id(fa_coin_dual_faucet_created: &FACoinDualFaucetCreated): option::Option<address> {
        fa_coin_dual_faucet_created.id
    }

    public(friend) fun set_fa_coin_dual_faucet_created_id(fa_coin_dual_faucet_created: &mut FACoinDualFaucetCreated, id: address) {
        fa_coin_dual_faucet_created.id = option::some(id);
    }

    public fun fa_coin_dual_faucet_created_provider(fa_coin_dual_faucet_created: &FACoinDualFaucetCreated): address {
        fa_coin_dual_faucet_created.provider
    }

    public fun fa_coin_dual_faucet_created_x_token_type(fa_coin_dual_faucet_created: &FACoinDualFaucetCreated): address {
        fa_coin_dual_faucet_created.x_token_type
    }

    public fun fa_coin_dual_faucet_created_y_token_type(fa_coin_dual_faucet_created: &FACoinDualFaucetCreated): String {
        fa_coin_dual_faucet_created.y_token_type
    }

    public fun fa_coin_dual_faucet_created_x_amount(fa_coin_dual_faucet_created: &FACoinDualFaucetCreated): u64 {
        fa_coin_dual_faucet_created.x_amount
    }

    public fun fa_coin_dual_faucet_created_y_amount(fa_coin_dual_faucet_created: &FACoinDualFaucetCreated): u64 {
        fa_coin_dual_faucet_created.y_amount
    }

    public(friend) fun new_fa_coin_dual_faucet_created<Y>(
        provider: address,
        x_token_type: address,
        y_token_type: String,
        x_amount: u64,
        y_amount: u64,
    ): FACoinDualFaucetCreated {
        FACoinDualFaucetCreated {
            id: option::none(),
            provider,
            x_token_type,
            y_token_type,
            x_amount,
            y_amount,
        }
    }

    struct FACoinDualFaucetDropped has store, drop {
        id: address,
        version: u64,
        receiver: address,
        x_amount: u64,
        y_amount: u64,
        x_token_type: address,
        y_token_type: String,
    }

    public fun fa_coin_dual_faucet_dropped_id(fa_coin_dual_faucet_dropped: &FACoinDualFaucetDropped): address {
        fa_coin_dual_faucet_dropped.id
    }

    public fun fa_coin_dual_faucet_dropped_receiver(fa_coin_dual_faucet_dropped: &FACoinDualFaucetDropped): address {
        fa_coin_dual_faucet_dropped.receiver
    }

    public fun fa_coin_dual_faucet_dropped_x_amount(fa_coin_dual_faucet_dropped: &FACoinDualFaucetDropped): u64 {
        fa_coin_dual_faucet_dropped.x_amount
    }

    public fun fa_coin_dual_faucet_dropped_y_amount(fa_coin_dual_faucet_dropped: &FACoinDualFaucetDropped): u64 {
        fa_coin_dual_faucet_dropped.y_amount
    }

    public fun fa_coin_dual_faucet_dropped_x_token_type(fa_coin_dual_faucet_dropped: &FACoinDualFaucetDropped): address {
        fa_coin_dual_faucet_dropped.x_token_type
    }

    public fun fa_coin_dual_faucet_dropped_y_token_type(fa_coin_dual_faucet_dropped: &FACoinDualFaucetDropped): String {
        fa_coin_dual_faucet_dropped.y_token_type
    }

    public(friend) fun new_fa_coin_dual_faucet_dropped<Y>(
        id: address,
        fungible_asset_coin_dual_faucet: &FungibleAssetCoinDualFaucet<Y>,
        receiver: address,
        x_amount: u64,
        y_amount: u64,
        x_token_type: address,
        y_token_type: String,
    ): FACoinDualFaucetDropped {
        FACoinDualFaucetDropped {
            id,
            version: version(fungible_asset_coin_dual_faucet),
            receiver,
            x_amount,
            y_amount,
            x_token_type,
            y_token_type,
        }
    }


    public(friend) fun update_version_and_add<Y>(obj_addr: address, fungible_asset_coin_dual_faucet: FungibleAssetCoinDualFaucet<Y>) acquires ObjectController {
        fungible_asset_coin_dual_faucet.version = fungible_asset_coin_dual_faucet.version + 1;
        let extend_ref = &borrow_global<ObjectController>(obj_addr).extend_ref;
        let object_signer = object::generate_signer_for_extending(extend_ref);
        private_add_fungible_asset_coin_dual_faucet(&object_signer, fungible_asset_coin_dual_faucet)
    }

    public(friend) fun add_fungible_asset_coin_dual_faucet<Y>(object_signer: &signer, fungible_asset_coin_dual_faucet: FungibleAssetCoinDualFaucet<Y>) {
        assert!(fungible_asset_coin_dual_faucet.version == 0, EInappropriateVersion);
        private_add_fungible_asset_coin_dual_faucet(object_signer, fungible_asset_coin_dual_faucet);
    }

    public(friend) fun remove_fungible_asset_coin_dual_faucet<Y>(obj_addr: address): FungibleAssetCoinDualFaucet<Y> acquires FungibleAssetCoinDualFaucet {
        move_from<FungibleAssetCoinDualFaucet<Y>>(obj_addr)
    }

    fun private_add_fungible_asset_coin_dual_faucet<Y>(object_signer: &signer, fungible_asset_coin_dual_faucet: FungibleAssetCoinDualFaucet<Y>) {
        move_to(object_signer, fungible_asset_coin_dual_faucet);
    }

    public(friend) fun delete_fungible_asset_coin_dual_faucet(obj_addr: address) acquires ObjectController {
        let ObjectController {
            extend_ref: _extend_ref,
            delete_ref,
            transfer_ref: _transfer_ref,
        } = move_from<ObjectController>(
            obj_addr
        );
        object::delete(delete_ref)
    }

    public(friend) fun transfer_fungible_asset_coin_dual_faucet(obj_addr: address, to: address) acquires ObjectController {
        let transfer_ref = &borrow_global<ObjectController>(obj_addr).transfer_ref;
        let linear_transfer_ref = object::generate_linear_transfer_ref(transfer_ref);
        object::transfer_with_ref(linear_transfer_ref, to)
    }

    public(friend) fun get_fungible_asset_coin_dual_faucet<Y>(obj_addr: address): pass_object::PassObject<FungibleAssetCoinDualFaucet<Y>> acquires FungibleAssetCoinDualFaucet {
        let fungible_asset_coin_dual_faucet = remove_fungible_asset_coin_dual_faucet(obj_addr);
        pass_object::new_with_address(fungible_asset_coin_dual_faucet, obj_addr)
    }

    public(friend) fun return_fungible_asset_coin_dual_faucet<Y>(fungible_asset_coin_dual_faucet_pass_obj: pass_object::PassObject<FungibleAssetCoinDualFaucet<Y>>) acquires ObjectController {
        let (fungible_asset_coin_dual_faucet, obj_addr) = pass_object::extract_value_and_address(fungible_asset_coin_dual_faucet_pass_obj);
        let extend_ref = &borrow_global<ObjectController>(obj_addr).extend_ref;
        let object_signer = object::generate_signer_for_extending(extend_ref);
        private_add_fungible_asset_coin_dual_faucet(&object_signer, fungible_asset_coin_dual_faucet);
    }

    public(friend) fun borrow_mut<Y>(fungible_asset_coin_dual_faucet_pass_obj: &mut pass_object::PassObject<FungibleAssetCoinDualFaucet<Y>>): &mut FungibleAssetCoinDualFaucet<Y> {
        pass_object::borrow_mut(fungible_asset_coin_dual_faucet_pass_obj)
    }

    public(friend) fun object_signer(obj_addr: address): signer acquires ObjectController {
        let extend_ref = &borrow_global<ObjectController>(obj_addr).extend_ref;
        object::generate_signer_for_extending(extend_ref)
    }

    public(friend) fun drop_fungible_asset_coin_dual_faucet<Y>(fungible_asset_coin_dual_faucet: FungibleAssetCoinDualFaucet<Y>) {
        let FungibleAssetCoinDualFaucet {
            version: _version,
            x_reserve: _x_reserve,
            y_reserve,
        } = fungible_asset_coin_dual_faucet;
        aptos_framework::coin::destroy_zero(y_reserve);
    }

    public(friend) fun emit_fa_coin_dual_faucet_created(fa_coin_dual_faucet_created: FACoinDualFaucetCreated) acquires Events {
        assert!(exists<Events>(genesis_account::resource_account_address()), ENotInitialized);
        let events = borrow_global_mut<Events>(genesis_account::resource_account_address());
        event::emit_event(&mut events.fa_coin_dual_faucet_created_handle, fa_coin_dual_faucet_created);
    }

    public(friend) fun emit_fa_coin_dual_faucet_dropped(fa_coin_dual_faucet_dropped: FACoinDualFaucetDropped) acquires Events {
        assert!(exists<Events>(genesis_account::resource_account_address()), ENotInitialized);
        let events = borrow_global_mut<Events>(genesis_account::resource_account_address());
        event::emit_event(&mut events.fa_coin_dual_faucet_dropped_handle, fa_coin_dual_faucet_dropped);
    }

}
