// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module dual_faucet::fungible_asset_coin_dual_faucet_aggregate {
    use aptos_framework::object::{Self, Object};
    use dual_faucet::fungible_asset_coin_dual_faucet::{Self, FungibleAssetCoinDualFaucet};
    use std::signer;

}
